### ISSUE TITLE
Warning 56 (assignment to non-mutable value) is missing the filename

### ISSUE THREAD

**Issue by mshinwell** [OCamlPro/flambda-task-force#129]
It always says file "none"

**Comment by marklrh** [comment]
can confirm that this problem arises at [L418 of closure_conversion.ml](https://github.com/chambart/ocaml-1/blob/flambda_trunk/middle_end/closure_conversion.ml#L418)

I am looking for an appropriate value of type ``loc``, then I can use ``Debuginfo.from_location`` to create a correct ``Debuginfo.t``.

However, I can't fine any. I can only get compilation unit info through ``current_unit_id`` from ``t`` at [L156 of closure_conversion.ml](https://github.com/chambart/ocaml-1/blob/flambda_trunk/middle_end/closure_conversion.ml#L156)

**Comment by mshinwell** [comment]
I'm not actually sure how to fix this properly without major changes.  The whole propagation of debug info is unsatisfactory.  For the moment maybe you could add a "filename" member to the type "t" in closure_conversion.ml, and use that to build a Debuginfo.t that has zero line and column numbers, but at least has the filename.  It shouldn't be too hard to propagate (via middle_end/middle_end.ml, from optcompile.ml or whatever) the filename through.  Can you try that?

**Comment by marklrh** [comment]
Sorry for late reply because I am kind of busy recently.

Here is an attempt with minimum amount of modification: https://github.com/marklrh/ocaml/commit/b020b3711bd08cf1922c26c8dfa77369b6390874

For file [bad.ml](https://gist.github.com/marklrh/66d8e8ec1ddb34cdd779):

the warning used to be:
![image](https://cloud.githubusercontent.com/assets/3656079/12958691/c866cfd0-cfe7-11e5-9fe1-865fb18ba11d.png)
now:
![image](https://cloud.githubusercontent.com/assets/3656079/12958699/d6f5bfc0-cfe7-11e5-9d3d-a50eff7b9f98.png)

**Comment by mshinwell** [comment]
We're going to use your existing patch, thanks!  (One day we will try to fix Translcore so that the locations are propagated correctly independently of the debugging events.)
