### ISSUE TITLE
Increased stack usage and other regressions with ocamlopt in non-flambda mode

### ISSUE THREAD

**Issue by alainfrisch** [OCamlPro/flambda-task-force#133]
(Already reporting by email.)

Trying the compile the lu-decomposition benchmark from https://github.com/AltGr/ocaml-numerical-analysis/archive/1.0.tar.gz, I get a "Stack overflow" error from ocamlopt after configuring the branch *without* passing -flambda, while ocamlopt from OCaml trunk works fine.  Playing with OCAMLRUNPARAM=l=XXXX, I've found the approximate minimum stack size required to have ocamlopt compile this program:

  trunk: 270000
  flambda_trunk: 1050000
  flambda_trunk (with -flambda): 270000

Compilation time also increase:

 trunk: 1.13s
 flambda_trunk: 3.8s
 flambda_trunk (with -flambda): 5.9s

And so does the size of the generated .o file:

 trunk: 587kB
 flambda_trunk: 908kB
 flambda_trunk (with -flambda): 767kB

[EDIT: updated the .o size for -flambda after the fix for #134.]

**Comment by mshinwell** [comment]
@chambart Would you be able to look at what's going on here in non-flambda mode?
By the way, I think there may be a bug in flambda_trunk with regard to the factor of 8 involved with setting of the inlining threshold when in non-flambda mode.  I *think* this has been fixed in the patches I pushed to upstream trunk.  I was going to re-test once the merge has been finished.

**Comment by chambart** [comment]
Apparently, this is a merge problem in the flambda_trunk branch (flambda_merge does not have it).
I will try to fix the trunk merges cleanly in it.

**Comment by mshinwell** [comment]
Pierre says this has been fixed
