### ISSUE TITLE
Float arrays not being lifted

### ISSUE THREAD

**Issue by mshinwell** [OCamlPro/flambda-task-force#91]
From email:

The representation of float arrays can change depending on the size:

  let long_float_array = [| 1.; 2.; 3.; 4.; 5.; 6.; 7.; 8.; 9.; 10. |]
  let short_float_array = [| 1.; 2. |]

   long_float_array/1204 = (caml_obj_dup [|1. 2. 3. 4. 5. 6. 7. 8. 9. 10.|])
   short_float_array/1205 = (makearray[float] 0. 1.)

There are in fact two underlying problems there: we don't handle
makearray in lift_constants, so makearray cannot be converted to a
constant. And caml_obj_dup is preventing the long array to be considered
as a constant. We could get rid of it if we can prove that it applies at
toplevel and there is no reference to the inner array. This is could be
made by a simple pass.

The choice between makearray and obj_dup on a constant float array is
done in translcore. Another way to do that properly would be to delay
that choice until flambda_to_clambda or cmmgen and only generate
makearray. When a makearray is at toplevel, we could transform it to a
let_symbol.
￼
￼...

We think it should be sent through to flambda_to_clambda and decided
there.

**Comment by mshinwell** [comment]
This should now be fixed

**Comment by chambart** [comment]
I need to finished reading that carefully.

**Comment by mshinwell** [comment]
I've addressed @chambart 's code review comment by disallowing duplication of mutable arrays (although this isn't really checked very well).
@chambart : Have you finished reading?  If so we should close this issue.

**Comment by mshinwell** [comment]
@chambart Can you write down the final resolution as to what Leo and yourself were discussing in London on the float arrays from other compilation units issue?  Then I think we can close this.

**Comment by chambart** [comment]
There was a problem with duplicating immutable float array from other compilation units:
* duparray (_ , Symbol s) is considered as a constant
* There is no way to build it if the cmx file from the module declaring `s` is missing

The solution was to consider symbols from missing compilation units as not constant. It is an overapproximation since there is no problem for any other primitive to consider it so, but cmx file should be provided in general anyway.
